# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b7f98ce66fec7e5715e9af9c9d36ff5acf64efb8a34296bd4b9374524b3b6adbd460b38e7c7cbb02b46a7f8d606a1d66ad26754a1436b4bbb745b4644861a8

test:
  secret_key_base: b47508b69fcb5c93ef6237581cac1c161dd9524376cece532ccddec9d9e4bed47bb7c8b70ea3482b48b527d764b7a8ad4d0cf39b064e3894f1abfa3855e5e1c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
